# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Dockerize .NET web aoolication

on: push

jobs:
  building-container:
    name: Build Docker container image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish to Docker Hub 
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER-USERNAME }}
        password: ${{ secrets.DOCKER-PASSWORD }}
        repository: lyvanthien/dotnet-new
        tags: latest, ${{ github.run_number }}
